name: open_agenda_monorepo

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  analyze:
    run: flutter analyze .
    exec:
      concurrency: 1
  
  format:
    run: dart format . --set-exit-if-changed
    exec:
      concurrency: 1
  
  test:
    run: flutter test
    exec:
      concurrency: 1
  
  build:android:
    run: flutter build apk --release
    packageFilters:
      dirExists: android
    exec:
      concurrency: 1
  
  build:ios:
    run: flutter build ios --release --no-codesign
    packageFilters:
      dirExists: ios
    exec:
      concurrency: 1

  codegen:
    run: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
    exec:
      concurrency: 1

ide:
  intellij:
    enabled: true
