name: open_agenda
description: Open Agenda - Comprehensive K-12 educational management app with modern UI/UX
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Internal package
  open_agenda_core:
    path: ../../packages/core
  
  # Platform
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
